name: gendered
description: Gendered
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.4"

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.15
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  meta: ^1.15.0
  xml: ^6.5.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/svg/
    - assets/nouns/de/nouns.json
  fonts:
    - family: OutfitRegular
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
